// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPeu9J6nayDzHGmKWzEwVss_-MXZ7nFYM',
    appId: '1:252933383262:web:88419d167f1d5dc24380cf',
    messagingSenderId: '252933383262',
    projectId: 'voltify-f364a',
    authDomain: 'voltify-f364a.firebaseapp.com',
    storageBucket: 'voltify-f364a.firebasestorage.app',
    measurementId: 'G-DF44LVQ40N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSHkQogNvqQPMJeKj6p0NGNLZK-HPFog',
    appId: '1:252933383262:android:ab826565ce62b4f94380cf',
    messagingSenderId: '252933383262',
    projectId: 'voltify-f364a',
    storageBucket: 'voltify-f364a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_ctXWVs11UZCmMzEq2h_RDityTqaVyM',
    appId: '1:252933383262:ios:a0b168ba3d8034344380cf',
    messagingSenderId: '252933383262',
    projectId: 'voltify-f364a',
    storageBucket: 'voltify-f364a.firebasestorage.app',
    iosBundleId: 'com.example.voltify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_ctXWVs11UZCmMzEq2h_RDityTqaVyM',
    appId: '1:252933383262:ios:a0b168ba3d8034344380cf',
    messagingSenderId: '252933383262',
    projectId: 'voltify-f364a',
    storageBucket: 'voltify-f364a.firebasestorage.app',
    iosBundleId: 'com.example.voltify',
  );
}
